# Этап 2: статический пароль. На этапе 7 его заменит Vault (динамические креды).
apiVersion: v1
kind: Secret
metadata:
  name: pg-app-secret
  namespace: shortener
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: shortener
  password: lab-password-change-me
