apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shortener-api
  namespace: shortener
spec:
  selector:
    matchLabels:
      app: shortener-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  namespace: shortener
spec:
  selector:
    matchLabels:
      app: redis
  endpoints:
    - port: metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kminion
  namespace: shortener
spec:
  selector:
    matchLabels:
      app: kminion
  endpoints:
    - port: metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: clicks-consumer
  namespace: shortener
spec:
  selector:
    matchLabels:
      app: clicks-consumer
  podMetricsEndpoints:
    - port: metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-resources
  namespace: shortener
spec:
  selector:
    matchLabels:
      strimzi.io/kind: Kafka
  podMetricsEndpoints:
    - port: tcp-prometheus
      interval: 30s
